# Generated by Django 5.2.11 on 2026-03-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Veiculo',
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AddField(
            model_name='produto',
            name='ano',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='motor',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
