# Generated by Django 5.2.11 on 2026-03-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_produto_categoria_alter_produto_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default='motor', max_length=50),
            preserve_default=False,
        ),
    ]
